import { createPdfExport } from "@algolens/documentation";
import { exportHtml } from "./html-exporter.js";
import { exportJson } from "./json-exporter.js";
import { exportMarkdown } from "./markdown-exporter.js";
import type { ExportData, ExportFormat, ExportResult } from "./types.js";

export async function exportResults(format: ExportFormat, data: ExportData): Promise<ExportResult> {
  switch (format) {
    case "json":
      return exportJson(data);
    case "markdown":
      return exportMarkdown(data);
    case "html":
      return exportHtml(data);
    case "pdf": {
      const documentation = {
        title: data.title,
        overview: "AlgoLens exported analysis results.",
        functions: [],
        classes: [],
        architectureSummary: "Generated by the AlgoLens export engine.",
        reports: Object.entries(data.reports ?? {}).map(([name, report]) => ({
          type: "project" as const,
          title: name,
          content: JSON.stringify(report, null, 2),
        })),
      };

      return createPdfExport(documentation);
    }
    default:
      throw new Error("Unsupported export format");
  }
}
